# Generated by Django 6.0.4 on 2026-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=30)),
                ("modelo", models.CharField(max_length=50)),
                ("anio", models.IntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("color", models.CharField(max_length=20)),
            ],
        ),
    ]
