# Generated by Django 6.0.4 on 2026-04-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='vendedor',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='autos', to='autos.vendedor'),
        ),
    ]
