# Generated by Django 6.0.4 on 2026-04-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_vendedor_auto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
