# Generated by Django 6.0.4 on 2026-05-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_auto_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos_images'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
